name       : tcl
version    : 8.6.6
release    : 4
source     :
    - http://downloads.sourceforge.net/tcl/tcl8.6.6-src.tar.gz : a265409781e4b3edcc4ef822533071b34c3dc6790b893963809b9fe221befe07
license    :
    - BSD
summary    : tcl (Tool Command Language)
libsplit   : no
patterns   :
    - docs : /usr/share/man/mann
    - docs : /usr/share/man/man3
description: |
    Tcl is a powerful but easy to use dynamic programming language suitable for a wide range of uses including web and desktop applications, along with networking, administration, and more.
setup      : |
    pushd unix
    %configure --enable-64bit
build      : |
    pushd unix
    %make
install    : |
    pushd unix
    %make_install
    ln -sv /usr/bin/tclsh8.6 $installdir/usr/bin/tclsh
